### ISSUE TITLE
Case sensitivity for several functions

### ISSUE THREAD

**Issue by RobThree** [dleitee/strman#1]
I think (at least) the following functions would benefit from an extra (optional) `caseSensitive` (`true|false`) argument: 

`endsWith`, `ensureLeft`, `ensureRight`, `indexOf`, `lastIndexOf`, `removeLeft`, `removeRight`, `replace`, `startsWith`

**Comment by dleitee** [comment]
Thanks for the feedback.
I will implement as soon as possible.

**Comment by dleitee** [comment]
endsWith, startsWith, ensureLeft, ensureRight,
