### ISSUE TITLE
RemoveNonChars is transliteration

### ISSUE THREAD

**Issue by claudioc** [dleitee/strman#12]
Hi,

nice library! I guess the `RemoveNonChars` method is wrongly named (the alphabet of my mother tongue contains àé characters and I hardly consider them "non-chars"). Anyway, I think the right name for what the method does is "transliteration" (https://en.wikipedia.org/wiki/Transliteration).

Thanks!

**Comment by dleitee** [comment]
Hi @claudioc, 

Thank you for this feedback. I will rename method to `transliterate`. 

What you think?

**Comment by claudioc** [comment]
I think it's perfect :) Thanks!
