### ISSUE TITLE
Support string formatting/interpolation?

### ISSUE THREAD

**Issue by phil-r** [dleitee/strman#15]
Do you have any plans to support string formatting? 
e.g. `"Hello {0}".format("world")` [example implementation](http://stackoverflow.com/questions/610406/javascript-equivalent-to-printf-string-format)
This is required quite often and template strings aren't suitable in every case

**Comment by dleitee** [comment]
Hi @phil-r,
Well remembered, I'll put in the plans for the version 1.2.0.
Thank you.

**Comment by phil-r** [comment]
Cool! ping me if you need any help with that ;)

**Comment by dleitee** [comment]
@phil-r #21 TO-DO v1.2.0
