### ISSUE TITLE
Allow trim() to also trim on inputted character(s)?

### ISSUE THREAD

**Issue by ahauth** [dleitee/strman#17]
One thing that is in the .NET framework for string libraries is an expanded use of the .trim() method, where not only do you have the option to trim on whitespace, but also allow you to trim on other characters given

Say we have a string `var myString = '##@#ASDF###'`

You could make the call:
`var myTrimmedString = trim(myString, '#')   // myTrimmedString = '@#ASDF'`

**Comment by dleitee** [comment]
Hi @ahauth,
I'll put in the plans for the version 1.2.0.
Thank you.
