### ISSUE TITLE
Warning issued in webpack build

### ISSUE THREAD

**Issue by benarmston** [dleitee/strman#2]
When including strman in an ES6 module built with webpack I'm presented with the following warning.

```
WARNING in ./~/strman/dist/strman.js
Critical dependencies:
1:404-411 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
 @ ./~/strman/dist/strman.js 1:404-411
```

The module that imports it does so with 

```
import {toCamelCase} from 'strman';
```

It would be very good if you could provide a build which didn't produce that warning.

**Comment by figalex** [comment]
I just had the same warning with webpack, seems like it is complaining about the minified file.

**Comment by benarmston** [comment]
That would be my guess as well. I've managed to remove the warning by modifying my webpack configuration to include

```
{
  module: {
    noParse: /node_modules\/strman/
  }
}
```

But I'm not particularly keen on that.

**Comment by Zhouzi** [comment]
The solution would be to publish a non-bundled, ES5 version along with the npm package so webpack doesn't bundle it twice.

**Comment by dleitee** [comment]
@benarmston @Zhouzi I'll provide.

**Comment by dleitee** [comment]
@Zhouzi you can see this commit 0a63f6e?

**Comment by Zhouzi** [comment]
Looks ok to me, could @benarmston and @figalex confirm it's working fine?

**Comment by benarmston** [comment]
It's working for me too. @dleitee thanks for fixing this and for creating a dependency-free string manipulation library.

**Comment by dleitee** [comment]
@benarmston very good. If you need anything, I'm at your disposal.
