### ISSUE TITLE
containsAll return true if needles be empty

### ISSUE THREAD

**Issue by sijad** [dleitee/strman#20]
is this ok?

**Comment by dleitee** [comment]
I believe that yes, you have an opinion on?

**Comment by sijad** [comment]
I just was wonder because [Stringy](https://github.com/danielstjules/Stringy/blob/master/src/Stringy.php#L229) has a different behaviour

**Comment by dleitee** [comment]
@sijad 
Reading some documentation, I understood that if needles is empty, contains should return false.

I'll provide the bugfix.

Thank you.
