### ISSUE TITLE
Add typescript typings to DefinitelyTyped/DefinitelyTyped

### ISSUE THREAD

**Issue by apinnecke** [dleitee/strman#3]
Hi,

would be great if one could add typings for this lib to https://github.com/DefinitelyTyped/DefinitelyTyped in order to be able to use in TypeScript. 🚀 

Thx for building this lib!

**Comment by apinnecke** [comment]
Hey @dleitee , what's the state here? Was not able to find them in DefinitelyTyped repo? 😟

**Comment by dleitee** [comment]
Hey @apinnecke, this issue isn't in the plans for this project. The idea is just to create a string handler with vanilla javascript.

Thanks

**Comment by imkmf** [comment]
For future people who end up at this issue–you can define your own manual typings if needed. I don't have the time to do this for the whole project, but I have a vendor types file with this included... extrapolating it to other methods should be pretty straightforward.

```typescript
declare module 'strman' {
  const slugify: (str: string) => string;
  export { slugify };
}
```
