### ISSUE TITLE
Titlecase?

### ISSUE THREAD

**Issue by mikeerickson** [dleitee/strman#40]
Is there a titleCase routine?  Cant find by that specific (or partial) name but guessing it might be there with a different name ;-)

**Comment by dleitee** [comment]
Hi @mikeerickson,
Thanks for the question.
It would be something similar to the [studly caps](https://github.com/dleitee/strman/blob/master/src/string.cases.js#L62)?

```javascript
/**
 * Transform to StudlyCaps.
 * @playground
 * var toStudlyCaps = require('strman').toStudlyCaps;
 * let title = "A Javascript string manipulation library.";
 * let result = toStudlyCaps(title);
 * @param {String} value - The String!.
 * @return {String} - String in StudlyCaps.
 */
const toStudlyCaps = value => {
    let string = value.replace(/[\-_\s]+(.)?/g,
                            (match, chr) => chr ? toUpperCase(chr) : '');
    return toUpperCase(string.substr(0, 1)) + string.substr(1);
};

export {toStudlyCaps};
```

**Comment by mikeerickson** [comment]
@dleitee perfect, thx! Figured it was there somewhere

**Comment by mikeerickson** [comment]
@dleitee I will be creating an Angular filter library (unless one already exists)?

**Comment by dleitee** [comment]
@mikeerickson 
Thank you for this. There is not anything like that, you want help?
