### ISSUE TITLE
Documentation page takes a lot of time and CPU to open

### ISSUE THREAD

**Issue by figalex** [dleitee/strman#54]
Every time I try to open the documentation page (https://doclets.io/dleitee/strman/master) my browser (safari) hangs and my CPU starts to run at 90%.

**Comment by dleitee** [comment]
@figalex thanks for the info, I am working on the site for this documentation. The doclets.io was just a palliative solution.

**Comment by dleitee** [comment]
@figalex I am creating a strman v2.0.0 and I will create a new website. Thanks
