### ISSUE TITLE
 _s is not defined error after minification

### ISSUE THREAD

**Issue by sgadekar81** [dleitee/strman#57]
i am using _s.countSubstr(); before minification it is working fine but after minification it is giving me error _s is not defined. i have tried to inject dependency _s into my ctrl function so that minification can skip that _s from renaming it but it also not working for me, can anyone help me out?

**Comment by dleitee** [comment]
@sgadekar81  How are you using the library?

```
<script src="./bower_components/strman/dist/strman.js"></script>
var result = _s.isString('strman');
// result => true
```
