### ISSUE TITLE
Doclets site unusable because of examples

### ISSUE THREAD

**Issue by mightyiam** [dleitee/strman#65]
The sheer amount of examples and the way they are causing the page to repeatedly reflow...

**Comment by dleitee** [comment]
I'm working on a new site, in a few weeks, we will have new documentation.

**Comment by mightyiam** [comment]
Cool!

**Comment by dleitee** [comment]
Hey... see this [https://dleitee.github.io/strman/](https://dleitee.github.io/strman/)

**Comment by mightyiam** [comment]
Beautiful, bro.
