### ISSUE TITLE
Give credit to or mention Stringy

### ISSUE THREAD

**Issue by danielstjules** [dleitee/strman#7]
Hey, nice library! Would be great if you could mention where some of this code was taken from, since it was originally distributed under MIT. In particular, your big list of ascii chars: https://github.com/dleitee/strman/blob/master/src/lib/ascii.js Which seem to all be taken directly from: https://github.com/danielstjules/Stringy/blob/master/src/Stringy.php#L1601-L1756

Anyway, great work with it :)

**Comment by dleitee** [comment]
Surely, his library was a great inspiration. Thank you.
