### ISSUE TITLE
Docs on a website

### ISSUE THREAD

**Issue by YannBertrand** [dleitee/strman#8]
It would be convenient to have a clean website like https://lodash.com/docs.

**Comment by dleitee** [comment]
@YannBertrand  Sure, I'll provide.

**Comment by JexCheng** [comment]
ESDoc is a simple and uniform choice：
https://esdoc.org/

**Comment by dleitee** [comment]
@YannBertrand 
We have a temporary site for the documentation: [https://doclets.io/dleitee/strman/master](https://doclets.io/dleitee/strman/master)
